In [2]:
from numpy import arange as arg

start_step = int(input("enter the start range of steps creations=>"))
end_step = int(input("enter the end range of steps creations=>"))
nu= arg(start_step,end_step+1)


# create steps
for lp in nu:
    print(f"\nindex{[lp]}")
    print(f"here the step is =>{lp}\n")
    print(f"here the result:~>{arg(1, end_step+1, lp)}")

enter the start range of steps creations=> 1
enter the end range of steps creations=> 10



index[1]
here the step is =>1

here the result:~>[ 1  2  3  4  5  6  7  8  9 10]

index[2]
here the step is =>2

here the result:~>[1 3 5 7 9]

index[3]
here the step is =>3

here the result:~>[ 1  4  7 10]

index[4]
here the step is =>4

here the result:~>[1 5 9]

index[5]
here the step is =>5

here the result:~>[1 6]

index[6]
here the step is =>6

here the result:~>[1 7]

index[7]
here the step is =>7

here the result:~>[1 8]

index[8]
here the step is =>8

here the result:~>[1 9]

index[9]
here the step is =>9

here the result:~>[ 1 10]

index[10]
here the step is =>10

here the result:~>[1]


In [6]:
import numpy as np

here_the_1d_arr = np.arange(1, 100+1)
print(f"\nhere_the_1d_arr =>\n{here_the_1d_arr}")

after_the_reshape_conv_info_2d = here_the_1d_arr.reshape(10,10)
print(f"\nafter_the_reshape_conv_info_2d = >\n{after_the_reshape_conv_info_2d}")

now_i_want_to_conv_1d = after_the_reshape_conv_info_2d.ravel()
print(f"\now_i_want_to_conv_1d = >\n{now_i_want_to_conv_1d}")


here_the_1d_arr =>
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

after_the_reshape_conv_info_2d = >
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

ow_i_want_to_conv_1d = >
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  2