In [1]:
import numpy as np

# martix create 

In [2]:
# => (row, cols)
arr_1s = np.ones([5,5])

In [3]:
arr_1s.dtype

dtype('float64')

In [4]:
# type cast with ones() 'float to int'
int_arr = np.ones((3,5), dtype=int) #you cant understand the press shift + tab see the doc of 'oncs()'
int_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
# zeros matrix
print(f"float~>\n {np.zeros((2,2))}")
f"type cast ~>{np.zeros((2,4), dtype=int, )}"

float~>
 [[0. 0.]
 [0. 0.]]


'type cast ~>[[0 0 0 0]\n [0 0 0 0]]'

In [6]:
print(f"array with true\n{np.ones((4, 4), dtype=bool)}")
print(f"\narray with false\n{np.zeros((4, 4), dtype=bool)}")
print(f"\narray with false with 'str'\n{np.zeros((4, 4), dtype=str)}")

array with true
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

array with false
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]

array with false with 'str'
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [7]:
# empty matrix
em_mx = np.empty((3, 3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.85763116e-321]
 [3.11493533e+150 4.73600036e+170 9.88131292e-324]]


# arange()

In [8]:
# np.arange(start, end, steps)
print(np.arange(1, 100+1))

#using steps
print(f"\nHere the array is even ~> {np.arange(1, 100+1, 2)}")

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Here the array is even ~> [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [9]:
start_step = int(input("enter the start range of steps creations=>"))
end_step = int(input("enter the end range of steps creations=>"))
nu= np.arange(start_step,end_step+1)


# create steps
for lp in nu:
    print(f"\nhere the step is =>{lp}\n")
    print(np.arange(1, end_step+1, lp))

enter the start range of steps creations=> 1
enter the end range of steps creations=> 10



here the step is =>1

[ 1  2  3  4  5  6  7  8  9 10]

here the step is =>2

[1 3 5 7 9]

here the step is =>3

[ 1  4  7 10]

here the step is =>4

[1 5 9]

here the step is =>5

[1 6]

here the step is =>6

[1 7]

here the step is =>7

[1 8]

here the step is =>8

[1 9]

here the step is =>9

[ 1 10]

here the step is =>10

[1]


# linspace()

In [10]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [11]:
arr_1d = np.arange(1,12+1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
# (matrix_row, matrix_col)
arr_1d.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# 3d
arr_1d.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
arr = np.arange(1, 12+1).reshape(2, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# ravel()

In [15]:
# here the ravel() function is used to 2d array into 1d array
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
here_the_1d_arr = np.arange(1, 100+1)
print(f"\nhere_the_1d_arr =>\n{here_the_1d_arr}")

after_the_reshape_conv_info_2d = here_the_1d_arr.reshape(10,10)
print(f"\nafter_the_reshape_conv_info_2d = >\n{after_the_reshape_conv_info_2d}")

now_i_want_to_conv_1d = after_the_reshape_conv_info_2d.ravel()
print(f"\now_i_want_to_conv_1d = >\n{now_i_want_to_conv_1d}")


here_the_1d_arr =>
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

after_the_reshape_conv_info_2d = >
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

ow_i_want_to_conv_1d = >
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  2

# flatten()

In [17]:
# here the flatten() function is used to multidimensional array into 1d array
after_the_reshape_conv_info_2d.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# transpose()

In [27]:
# here the transpose the matrix 
two_d_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [28]:
two_d_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]]).transpose()

In [37]:
print(f"here the normal matrix (4x2)\n{two_d_arr}\n and here the transpose matrix (2x4)\n {two_d_arr.transpose()}")

here the normal matrix (4x2)
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 and here the transpose matrix (2x4)
 [[1 2 3 4]
 [5 6 7 8]]
